### ISSUE TITLE
Respect system keyboard layout settings

### ISSUE THREAD

**Issue by kchanqvq** [neomacs-project/neomacs#51]

**Comment by kchanqvq** [comment]
@m4vnel by the way, can you describe a bit more detail about your problem with Spanish layout? Is it mainly about modifier keys, or letters are in different locations, or something else? Thanks!

**Comment by m4vnel** [comment]
Only the numbers and letters are in the same positions (and not always): parenthesis, signs, colon, semicolon, dashes... all these are in different positions, making editing practically impossible. Is not a problem with specifically the spanish layout, nearly every country / language has a different keymap Here you can see the differences:

![df77abcefeb30ea0f17c0070a73ebeedcef3f479](https://github.com/user-attachments/assets/cf9c8f61-a7fe-4502-a13c-80b8dc34832d)
![english-united-states-us-windows-kblayout-unilingual-2021_4c5e8bbb-3774-48d6-8483-2c910d84e173](https://github.com/user-attachments/assets/692a7c77-db5f-42d2-996c-631aa97f7f1b)

**Comment by kchanqvq** [comment]
Hi @m4vnel, I think I found where I'm supposed to look at. I can get the translated character by reading the `key` instead of `code` property for keyboard events from Electron.

My remaining question is whether we should outsource this to Electron (like other apps do), or do it ourselves (which is more flexible, because Electron's translation loses some information, like it cannot distinguish left and right ctrl). I guess we should take a look at how Emacs does this.

Can you try `M-: (read-event)` in GUI Emacs, then press some key that's different in US/spanish layout, and see what character Emacs reports? Thanks!

**Comment by kchanqvq** [comment]
In any case, I have pushed a patch to master (ecdbce3). If you can take a try, feel free to report back any problem!

**Comment by m4vnel** [comment]
I've remapped my Right Ctrl to Hyper for more modifier keys in Emacs, but I think the vast majority of users don't care about it, so letting Electron manage this will be easier (and safer).  Perhaps is more a philosophical issue :-D

These are the output of GUI Emacs to my dash key (your backslash one, top left in the picture above) and my 'ñ' key, your semicolon one:

`45 (#o55, #x2d, ?-)`

`241 (#o361, #xf1)`

**Comment by kchanqvq** [comment]
Thanks! It seems that Emacs translate the event early as well, which is also what my patch does. Feel free to give `master` a try.

That reminds me that by default characters outside [a-zA-Z] is not mapped to `self-insert-command`. You can fix it in `init.lisp` but maybe it's better to map a larger range to `self-insert-command` by default. Let me see what Emacs does…

**Comment by kchanqvq** [comment]
I bound ascii 128-255 to `self-insert-command` in 8558cf9.

**Comment by m4vnel** [comment]
Great! I'll wait for the next prebuilt, since I have not the tools to build it from source.

**Comment by kchanqvq** [comment]
@mmontone Thanks for you feedback! I'm closing this for now.
@m4vnel I just published a new release https://github.com/neomacs-project/neomacs/releases/tag/0.1.1

**Comment by m4vnel** [comment]
The keymap issue is fixed. Accents, though, are not working: "què", "sí" and the like. Perhaps the codification system are not set to UTF-8? I think is the default nowadays.

**Comment by kchanqvq** [comment]
@m4vnel Does the accent issue appear when inserting or when saving the files? I'm reopening this now.

**Comment by kchanqvq** [comment]
Actually, is this rather an input method issue? That would be a much bigger task: either support OS input method, or have our own input method framework (which I would prefer, because I always use Emacs input method instead of the OS one)...

**Comment by m4vnel** [comment]
The issue appears when inserting. The input method in my emacs is the default. 20 years ago I needed to change it (emacs mule) by right now there's no need anymore, the OS (better said X or Wayland, I guess) takes care of enabling accents or "dead keys" and emacs, as the rest of applications, happily uses it. 

If I ask emacs about input method or language environment, the answer is always "default" or "english". And the coding system is utf-8-unix.

**Comment by kchanqvq** [comment]
Neomacs uses utf-8 by default. The problem is probably about the system input method, which I don't use myself but I'll try to setup something so that I can test...

@m4vnel Are you on x11 or Wayland? I read that Electron might need some special flag to get input method working on Wayland (haven't tested because I don't have Wayland).

**Comment by m4vnel** [comment]
I'm in X11

**Comment by kchanqvq** [comment]
I researched this for a while and there does not seem to be an easy way... Electron's `before-input-event` seems to intercept events before they are passed to input methods. The solutions I found are all platform-dependent and hacky (like creating an invisible X window and sending key presses to it).

In case of dead keys, maybe it's easier to write a package that binds them to commands? (use `neomacs::read-key`). The next most viable option is probably to interface with ibus or fcitx, either is lots of work already.

**Comment by m4vnel** [comment]
Debian (Ubuntu, Mint...) uses `ibus` by default. Aside from that, I know not enough low-level programming to make any useful comment about what is easier, I'm sorry.

**Comment by kchanqvq** [comment]
Hi @m4vnel, sorry for the late response! I decided Neomacs will need its own input method framework anyways: in my experience, CJK input method in Emacs works much better than those by OS, because Emacs ones automatically turn on/off themselves depending on context (idk if that's relevant for Spanish). Therefore I can make something that works for you soon. From my understanding Spanish just needs two dead keys?

**Comment by kchanqvq** [comment]
I added a simple Latin input method in 5e43470. I'll include it in next release. People who can build from master are welcomed to test it :)

**Comment by kchanqvq** [comment]
@m4vnel a new prebuilt is out https://github.com/neomacs-project/neomacs/releases/tag/0.1.2, you'll need to `(setq *input-method-function* 'simple-input-method)`. Let me know if problem persists!

**Comment by m4vnel** [comment]
Is working fine! Great job :-)
