### ISSUE TITLE
Cannot display full completion frame when the width of the editor is too small

### ISSUE THREAD

**Issue by tesffitree** [neomacs-project/neomacs#52]
The completion frame would show up in wrong direction and cropped by editor's frame edge when the width of the editor is too small.
![屏幕截图 2024-11-21 201459](https://github.com/user-attachments/assets/a8a05542-dea2-415b-8d77-8c2d159086c4)
![屏幕截图 2024-11-21 201505](https://github.com/user-attachments/assets/c1fa2130-7742-4ba4-bbdc-c9c3fc603e95)

**Comment by kchanqvq** [comment]
I pushed a patch a110bf3. Does this fix it for you?

**Comment by kchanqvq** [comment]
I think this is fixed, closing it now.
