### ISSUE TITLE
App contents not resized after maximize

### ISSUE THREAD

**Issue by mmontone** [neomacs-project/neomacs#59]
If I resize the Electron window, then the application contents resize accordingly. But if I maximize the window, then the app contents don't get resized.
I've tried calling `redisplay-windows` when a `frame-focused`  event occurs, but it is not working.

![Peek 2024-11-23 13-12](https://github.com/user-attachments/assets/13180ea5-e973-40a2-8226-fb61833b36a4)

I'm on a Linux Mint window manager.

**Comment by kchanqvq** [comment]
I've encountered this question as well and I added listener to every event that I found in https://github.com/neomacs-project/neomacs/blob/1f8452e503251f2090b229dda11a8acba1beaaa8/main.js#L83 but it still didn't fix it…

**Comment by kchanqvq** [comment]
I think 2a90268 fixed it. Does it work now?

**Comment by mmontone** [comment]
It works! Awesome. It was a detail, but it was bothering me. Thanks!
