### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by mmontone** [neomacs-project/neomacs#62]
- [x] - Move the text cursor to the position in the buffer I click on with the mouse.
- [x] - Keep position in buffer after a `search-forward` command is canceled. At the moment, the buffer moves back to the position the search started.

**Comment by kchanqvq** [comment]
@mmontone On the second point, it should keep position if you press enter.

**Comment by mmontone** [comment]
Oh. My bad. Thanks!

**Comment by kchanqvq** [comment]
I think the first one would require some work. At the very least we need to be able to let JavaScript talk back to Lisp (Electron's main process only provides API to intercept keyboard events, not mouse events), which means we probably need to study how to setup Electron's IPC bridge using `preload.js` and such...

On the other hand, maybe turn off security features completely for local buffers would make life much easier. I can already see these get into the way: for example, currently no buffer has direct access to `file:///...` and have to abuse `neomacs://sys//...`. What do you think?

**Comment by kchanqvq** [comment]
I think I figured out mouse support, pushed 8a87e00. Item 1 should work now?

**Comment by mmontone** [comment]
Mm.. cursor still doesn't move for me as I click ..

**Comment by kchanqvq** [comment]
Hmmm, if you `(trace handle-event)` do you see events like `((:TYPE . "click") …)`? Also if you `M-x open-dev-tools` do you see JavaScript errors?

**Comment by mmontone** [comment]
When I click, handle-events get keydown event:

```
: (NEOMACS::HANDLE-EVENT #<BUFFER "*intro*" {0}>
                            ((:TYPE . "keyDown") (:KEY . "Alt")
                             (:CODE . "AltLeft") (:IS-AUTO-REPEAT)
                             (:IS-COMPOSING) (:SHIFT) (:CONTROL) (:ALT . T)
                             (:META) (:LOCATION . 1) (:--MODIFIERS . 2052)
                             (:MODIFIERS "alt" "left"))
                            #<FUNCTION NEOMACS::RUN-COMMAND>)
```

But `:location` parameter doesn't change.

**Comment by mmontone** [comment]
Wait .. I see errors in Electron console ...

**Comment by mmontone** [comment]
It is trying to load `assets/preload.js` , but I don't have such file ..

```
VM4 sandbox_bundle:2 Unable to load preload script: /home/marian/src/neomacs/assets/preload.js
(anonymous) @ VM4 sandbox_bundle:2
VM4 sandbox_bundle:2 Error: ENOENT: no such file or directory, open '/home/marian/src/neomacs/assets/preload.js'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1242:14)
    at async node:electron/js2c/browser_init:2:108345
    at async Promise.all (index 0)
    at async node:electron/js2c/browser_init:2:108281
    at async IpcMainImpl.<anonymous> (node:electron/js2c/browser_init:2:105246)
(anonymous) @ VM4 sandbox_bundle:2
VM4 sandbox_bundle:2 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
  Policy set or a policy with "unsafe-eval" enabled. This exposes users of
  this app to unnecessary security risks.
```

**Comment by mmontone** [comment]
![imagen](https://github.com/user-attachments/assets/79c1851e-ff5b-4ba6-a737-eb34754e3fe3)

**Comment by kchanqvq** [comment]
aha, my bad,  I forgot to add this file to the git repo. Just added in be5d5b3.
