### ISSUE TITLE
lwcells missing when building locally

### ISSUE THREAD

**Issue by noncom** [neomacs-project/neomacs#69]
Following the instructions from the main page brought up the error of `lwcells` missing and not found in Quicklisp.
I had to clone the lwcells to `<path-to>/quiklisp/local-projects` to resolve this.
Not sure how common this situation would be, but if the package is not present in Quicklisp, I would assume it should happen for more people? If so, maybe it's worth mentioning in the instruction.

Note: trying this out on Windows 10, but I'm not sure this makes a difference in this case.

**Comment by mmontone** [comment]
Instructions indicate to build with Ultralisp. But the build has been reported to work with Quicklisp too, cloning lwcells in local-projects: https://github.com/neomacs-project/neomacs/discussions/58#discussioncomment-11372587

**Comment by noncom** [comment]
Ok! Well, I was actually following the [Getting Started](https://github.com/neomacs-project/neomacs?tab=readme-ov-file#get-started) instruction, so not sure why this happed. If this is something that doesn't reproduce then there probably was some error from my side. Let's close this for now, and if I see this happening again, I'll reopen.
