### ISSUE TITLE
Ceramic not quickloading on Windows issue

### ISSUE THREAD

**Issue by noncom** [neomacs-project/neomacs#91]
Another Windows-specific issue, this time with ceramic: https://github.com/ceramic/ceramic/issues/66

Not much to do from neomacs side, I guess, but noting it here for info, and for easier tracking.

And wow, ceramic is ancient. Doesn't look like anyone is working on it these days, so I guess this might end up being a long one..

**Comment by mmontone** [comment]
I think this is the problem: https://github.com/ceramic/ceramic/issues/66#issuecomment-2556943898

**Comment by noncom** [comment]
Yep, thanks! Got it [sorted out](https://github.com/ceramic/ceramic/issues/66#issuecomment-2558242220).
